objectionary/lints

src/main/java/org/eolang/lints/comments/AsciiOnly.java
src/test/java/org/eolang/lints/comments/AsciiOnlyTest.java

In this pull I've added abusive character to show in the logs in `AsciiOnly.java` lint.
closes #14
History:
- **feat(#14): abusive character**
- **feat(#14): unused import**

feat(#14): show abusive character in AsciiOnly.java

---

src/main/resources/org/eolang/lints/metas/incorrect-package.xsl
src/main/resources/org/eolang/motives/metas/incorrect-package.md
src/test/resources/org/eolang/lints/catches-incorrect-package.yaml

In this pull I've introduced new lint: `incorrect-package`, that checks correctness of the `+package` meta tail.
closes #25
History:
- **feat(#25): incorrect-package**
- **feat(#25): motive**

feat(#25): incorrect-package lint

---

src/main/resources/org/eolang/lints/critical/package-contains-multiple-parts.xsl
src/main/resources/org/eolang/lints/metas/incorrect-package.xsl
src/main/resources/org/eolang/motives/critical/package-contains-multiple-parts.md
src/test/resources/org/eolang/lints/eo-packs/catches-incorrect-package.yaml
src/test/resources/org/eolang/lints/eo-packs/catches-package-contains-multiple-parts.yaml

In this pull I've introduced new lint: `package-contains-multiple-parts` that issues `critical` defect if more than one part is used in `+package` tail. `incorrect-package` lint now checks only the first part of the `+package` tail, instead of full one.
closes #54
History:
- **feat(#54): check the first part**
- **feat(#54): package-contains-multiple-parts**
- **feat(#54): motive**

feat(#54): package-contains-multiple-parts lint

---

src/main/resources/org/eolang/lints/critical/incorrect-rt-parts.xsl
src/main/resources/org/eolang/motives/critical/incorrect-rt-parts.md
src/test/resources/org/eolang/lints/eo-packs/catches-incorrect-rt-parts.yaml

In this pull I've introduced new lint: `incorrect-rt-parts` that issues `critical` defect in case `+rt` meta doesn't have 2 parts inside.
closes #53
History:
- **feat(#53): incorrect-rt-parts**
- **feat(#53): motive**
- **feat(#53): more errors**

feat(#53): incorrect-rt-parts lint

---

pom.xml
src/main/java/org/eolang/lints/Defect.java
src/test/java/org/eolang/lints/DefectTest.java
src/test/resources/META-INF/MANIFEST.MF

In this pull I've added new method to the `Defect` interface: `version()`, that returns version of the JAR from pom.xml file.
closes #60
History:
- **feat(#60): maven-model**
- **feat(#60): passes**
- **feat(#60): clean for pmd**

feat(#60): Defect.version

---

src/main/resources/org/eolang/lints/critical/unknown-rt.xsl
src/main/resources/org/eolang/motives/critical/unknown-rt.md
src/test/resources/org/eolang/lints/eo-packs/catches-unknown-rt.yaml
src/test/resources/org/eolang/lints/eo-packs/unknown-rt/allows-good-rt.yaml
src/test/resources/org/eolang/lints/eo-packs/unknown-rt/catches-unknown-rt.yaml

In this pull I've introduced new lint: `unknown-rt`, that issues `critical` error in case of the first part of runtime meta `+rt` is not in the allowed scope.
closes #52
History:
- **feat(#52): unknown-rt.xsl**
- **feat(#52): passes**

feat(#52): unknown-rt lint

---

src/main/resources/org/eolang/lints/metas/prohibited-package.xsl
src/test/resources/org/eolang/lints/eo-packs/prohibited-package/allows-packages-in-tests.yaml

In this pull I've updated `prohibited-package` lint in order to not issue defect when preserved packages are used in tests.
closes #71

feat(#71): prohibited-package allowed in tests

---

pom.xml
src/main/java/org/eolang/lints/ProgramLints.java
src/main/java/org/eolang/lints/misc/UnitTestIsNotVerb.java
src/test/java/org/eolang/lints/misc/UnitTestIsNotVerbTest.java
src/test/resources/org/eolang/lints/misc/test-object-is-not-verb-in-singular/bad-tests.eo
src/test/resources/org/eolang/lints/misc/test-object-is-not-verb-in-singular/good-tests.eo

In this pull request I've replaced `opennlp` with `stanford-corenlp` library, and made `UnitTestIsNotVerb` lint stricter by allowing only `VBZ` (Verb, 3rd person singular present) verbs in the test names.
closes #129

feat(#129): StanfordNLP in UnitTestIsNotVerb lint

---

src/test/java/org/eolang/lints/misc/UnitTestIsNotVerbTest.java
src/test/resources/org/eolang/lints/misc/test-object-is-not-verb-in-singular/regex-tests.eo

In this pull I've added new test case for `UnitTestIsNotVerb` lint: `regex-tests.eo` as real-world example for the lint.
ref #138

feat(#138): regex-tests.eo as test case for `UnitTestIsNotVerb` lint

---

src/main/resources/org/eolang/lints/comments/comment-is-too-wide.xsl
src/main/resources/org/eolang/motives/comments/comment-is-too-wide.md
src/test/resources/org/eolang/lints/packs/comment-is-too-wide/allows-good-comment-width.yaml
src/test/resources/org/eolang/lints/packs/comment-is-too-wide/allows-multiline-good-comment.yaml
src/test/resources/org/eolang/lints/packs/comment-is-too-wide/catches-multiline-wide-comment.yaml
src/test/resources/org/eolang/lints/packs/comment-is-too-wide/catches-too-wide-comment.yaml

In this pull I've introduced new lint: `comment-is-too-wide`, that issues `warning` defect if comment line is wider than 80 characters.
closes #16
History:
- **feat(#16): comment-is-too-wide**
- **feat(#16): multiline test cases**
- **feat(#16): passes with multilines**
- **feat(#16): indents**

feat(#16): comment-is-too-wide lint

---

src/main/resources/org/eolang/lints/critical/atom-with-data.xsl
src/main/resources/org/eolang/motives/critical/atom-with-data.md
src/test/resources/org/eolang/lints/packs/atom-with-data/allows-atom-with-nested-object.yaml
src/test/resources/org/eolang/lints/packs/atom-with-data/allows-atom-without-data.yaml
src/test/resources/org/eolang/lints/packs/atom-with-data/catches-atom-with-data.yaml

In this pull I've introduced new lint: `atom-with-data`, that issues `critical` defect in case atom has data inside.
closes #46

feat(#46): atom-with-data lint

---

src/main/resources/org/eolang/lints/critical/name-outside-of-abstract-object.xsl
src/main/resources/org/eolang/motives/critical/name-outside-of-abstract-object.md
src/test/resources/org/eolang/lints/packs/name-outside-of-abstract-object/allows-name-inside-abstract.yaml
src/test/resources/org/eolang/lints/packs/name-outside-of-abstract-object/catches-name-inside-not-abstract.yaml

In this pull I've introduced new lint: `name-outside-of-abstract`, that issues `critical` defect if `<o/>` has `@name` attribute, but his parent object is not abstract.
closes #68

feat(#68): name-outside-of-abstract-object lint

---

src/main/resources/org/eolang/lints/critical/package-without-tail.xsl
src/main/resources/org/eolang/motives/critical/package-without-tail.md
src/test/resources/org/eolang/lints/packs/package-without-tail/allows-package-with-tail.yaml
src/test/resources/org/eolang/lints/packs/package-without-tail/catches-empty-tail.yaml

In this pull, I've introduced new lint: `package-without-tail` that issues `critical` defect if `+package` meta is used without a tail.
closes #49

feat(#49): package-without-tail lint

---

src/main/java/org/eolang/lints/Program.java
src/main/java/org/eolang/lints/Programs.java
src/test/java/org/eolang/lints/ProgramTest.java
src/test/java/org/eolang/lints/ProgramsTest.java

In this pull I've removed declaration of `IOException` from `Program#defects()` in order to simplify the interaction with `Program.java` class.
ref #179
History:
- **fix(#179): IOException declaration off**
- **fix(#179): camel**

fix(#179): `Program#defects()` does not declare `IOException`

---

src/main/resources/org/eolang/lints/metas/architect-duplicate.xsl
src/main/resources/org/eolang/motives/metas/architect-duplicate.md
src/test/resources/org/eolang/lints/packs/architect-duplicate/allows-single.yaml
src/test/resources/org/eolang/lints/packs/architect-duplicate/catches-duplicate.yaml

In this pull I've implemented new lint: `architect-duplicate`, that ensures that only one `+architect` meta is in use.
closes #23

feat(#23): architect-duplicate-lint

---

.github/workflows/benchmark.yml
pom.xml
src/main/java/org/eolang/lints/Lint.java
src/main/java/org/eolang/lints/LtByXsl.java
src/main/java/org/eolang/lints/Program.java
src/main/java/org/eolang/lints/comments/LtAsciiOnly.java
src/main/java/org/eolang/lints/misc/LtTestNotVerb.java
src/main/java/org/eolang/lints/units/LtUnitTestMissing.java
src/test/java/org/eolang/lints/ProgramTest.java

In this pull I've added `BcProgram` for measuring each lint timings for XMIR-generated program during the benchmark.
In the Benchmark results we will have the following:
```md
Input: com/sun/jna/Pointer.class
Size of .class: 22Kb (22Kb bytes)
Size of .xmir after disassemble: 1Mb (1Mb bytes, 29630 lines)
Lint time: 42s (42355 ms)
alias-too-long (112 ms)
alias-without-tail (11 ms)
broken-alias-first (522 ms)
broken-alias-second (11 ms)
duplicate-aliases (37 ms)
...
```
closes #144
History:
- **feat(#144): timings**
- **feat(#144): typo**
- **feat(#144): Lint#name()**
- **feat(#144): present timings.csv**

feat(#144): Each Lint timings in benchmark

---

src/main/resources/org/eolang/lints/critical/atom-with-phi.xsl
src/main/resources/org/eolang/motives/critical/atom-with-phi.md
src/test/resources/org/eolang/lints/packs/atom-with-phi/allows-atoms-without-phi.yaml
src/test/resources/org/eolang/lints/packs/atom-with-phi/catches-atom-with-phi.yaml

In this pull I've implemented new lint: `atom-with-phi`, that issues `critical` defect in case atom has `@` (`φ`) attribute
closes #62

feat(#62): atom-with-phi lint

---

src/main/java/org/eolang/lints/PkWpa.java
src/main/java/org/eolang/lints/units/LtUnitTestWithoutLiveFile.java
src/main/resources/org/eolang/motives/units/unit-test-without-live-file.md
src/test/java/org/eolang/lints/units/LtUnitTestWithoutLiveFileTest.java

In this pull I've introduced new lint: `unit-test-without-live-file`, that issues `warning` defect in case unit test file does not match with live file, e.g. `foo-test -> bar`.
closes #112
History:
- **feat(#112): unit-test-without-live-file**
- **feat(#112): motive, valid xml**
- **feat(#112): wpa**

feat(#112): unit-test-without-live-file lint

---

.github/workflows/benchmark.yml

In this pull I've updated `benchmark.yml` to sort lint timings by `ms`, in the descending way.
closes #198

fix(#198): lint timings sorted by ms

---

src/main/resources/org/eolang/lints/misc/one-high-level-object.xsl
src/main/resources/org/eolang/motives/misc/one-high-level-object.md
src/test/resources/org/eolang/lints/packs/one-high-level-object/allows-multiple-objects-in-tests.yaml
src/test/resources/org/eolang/lints/packs/one-high-level-object/allows-one-program-object.yaml
src/test/resources/org/eolang/lints/packs/one-high-level-object/catches-multiple-program-objects.yaml

In this pull I've implemented new lint: `one-high-level-object`, that issues `warning` defect in case multiple high-level objects inside EO program.
closes #111

feat(#111): one-high-level-object lint

---

src/main/resources/org/eolang/lints/critical/pos-without-line.xsl
src/main/resources/org/eolang/motives/critical/pos-without-line.md
src/test/resources/org/eolang/lints/packs/pos-without-line/allows-line-with-pos.yaml
src/test/resources/org/eolang/lints/packs/pos-without-line/allows-line-without-pos.yaml
src/test/resources/org/eolang/lints/packs/pos-without-line/catches-pos-without-line.yaml

In this pull I've implemented new lint: `pos-without-line`, that issues `critical` defect in case `<o/>` has `@pos` without the `@line` attribute in XMIR.
closes #115

feat(#115): pos-without-line

---

src/test/resources/junit-platform.properties

In this pull I've updated default test JUnit timeout from `3s` to `10s` in order to keep windows builds green.
closes #212

bug(#212): puzzle for windows timeouts

---

src/main/resources/org/eolang/lints/metas/incorrect-package.xsl
src/test/resources/org/eolang/lints/packs/incorrect-package/allows-package-with-dollars.yaml
src/test/resources/org/eolang/lints/packs/incorrect-package/allows-package-with-fqn.yaml
src/test/resources/org/eolang/lints/packs/incorrect-package/allows-uppercase-letters-in-package.yaml

In this pull I've updated `incorrect-package` lint to support FQN names.
see #208

bug(#208): incorrect-package accepts `fqn`

---

src/test/resources/org/eolang/lints/packs/incorrect-package/allows-one-letter-names.yaml

In this pull I've added new test case for `incorrect-package`, that covers allowance of one-letter names, e.g.: `a.b.c`. The 
described issue was fixed after `incorrect-package` allows FQN-compliant names (see: #211).
closes #226

feat(#226): test case for one-letter-names in `incorrect-package`

---

src/main/java/org/eolang/lints/Defect.java
src/main/java/org/eolang/lints/Program.java
src/main/java/org/eolang/lints/Programs.java

In this pull I've updated JavaDocs of `Program.java`, `Programs.java`, `Defect.java`, now they mention XMIR, and resources about it.
see #209

bug(#209): XMIR links in `Program`, `Programs`, `Defect` JavaDoc

---

src/main/resources/org/eolang/lints/metas/incorrect-version.xsl
src/test/resources/org/eolang/lints/packs/incorrect-version/allows-good-versions.yaml
src/test/resources/org/eolang/lints/packs/incorrect-version/allows-maven-convention.yaml
src/test/resources/org/eolang/lints/packs/incorrect-version/catches-bad-maven-convention.yaml

In this PR I've updated `incorrect-version` lint to allow maven convention, e.g.: `1.0-SNAPSHOT` if specified in `+version` meta.
see #237

bug(#237): incorrect-version allows maven convention

---

src/main/java/org/eolang/lints/critical/LtIncorrectAlias.java
src/test/java/org/eolang/lints/critical/LtIncorrectAliasTest.java
src/test/resources/org/eolang/lints/critical/incorrect-alias/longer-alias.eo

In this PR I've updated `incorrect-alias` lint to scan the second part of `+alias` meta, if it has the second part inside.
Example:
```eo
+alias stdout org.eolang.io.stdout
```
In this case, `org/eolang/io/stdout.xmir` will be scanned.
see #227
History:
- **bug(#227): allowsLongerAlias**
- **bug(#227): scans second**
- **bug(#227): acceptsValidDirectoryWithLongerAlias**

bug(#227): incorrect-alias scans second part of longer `+alias`

---

src/main/resources/org/eolang/lints/critical/application-duality.xsl
src/main/resources/org/eolang/motives/critical/application-duality.md
src/test/resources/org/eolang/lints/packs/application-duality/allows-application-with-single-object.yaml
src/test/resources/org/eolang/lints/packs/application-duality/allows-application-without-as-attr.yaml
src/test/resources/org/eolang/lints/packs/application-duality/allows-full-application-with-nested-objects.yaml
src/test/resources/org/eolang/lints/packs/application-duality/allows-full-application.yaml
src/test/resources/org/eolang/lints/packs/application-duality/catches-dual-application.yaml
src/test/resources/org/eolang/lints/packs/application-duality/catches-duality-in-nested-objects.yaml
src/test/resources/org/eolang/lints/packs/application-duality/catches-many-dual-objects.yaml
src/test/resources/org/eolang/lints/packs/application-duality/ignores-abstract-objects.yaml

In this PR I've implemented `application-duality` lint that issues `critical` defect if object has an application with duality (`@as` attributes presence is mixed).
closes #248
History:
- **feat(#248): application-duality**
- **feat(#248): motive, more tests**

feat(#248): application-duality

---

pom.xml
src/it/lints-it/src/test/java/org/eolang/lints/it/LintsItTest.java
src/main/java/org/eolang/lints/LtByXsl.java
src/test/java/org/eolang/lints/PkByXslTest.java
src/test/java/org/eolang/lints/ProgramTest.java

In this PR I use `xnav` library to navigate over XML document elements. This significantly simplifies the code.
Closes: #216, #217

feat(#216): Integrate `xnav` Library

---

src/main/resources/org/eolang/lints/misc/incorrect-test-object-name.xsl
src/test/resources/org/eolang/lints/packs/incorrect-test-object-name/allows-numbers.yaml

In this PR I've updated `incorrect-test-object-name` lint to not complain about numbers in the test object name.
Example: `foo-i32` should not provoke defects.
see #267

bug(#267): `incorrect-test-object-name` allows numbers

---

src/test/resources/org/eolang/lints/packs/application-duality/allows-numbers-in-application.yaml

In this PR I've added test that proves the work of `application-duality` lint with EO test case
see #268

bug(#268): test for EO application-duality false alarm

---

src/main/resources/org/eolang/lints/misc/incorrect-test-object-name.xsl
src/test/resources/org/eolang/lints/packs/incorrect-test-object-name/allows-many-one-letter-parts.yaml
src/test/resources/org/eolang/lints/packs/incorrect-test-object-name/allows-one-letter-in-first.yaml
src/test/resources/org/eolang/lints/packs/incorrect-test-object-name/allows-one-letter-parts-with-numbers-inside.yaml
src/test/resources/org/eolang/lints/packs/incorrect-test-object-name/allows-one-letter-parts.yaml

In this PR I've updated regexp in `incorrect-test-object-name` lint, to allow one-letter-parts in test name.
see #272

bug(#272): `incorrect-test-object-name` allows one-letter-parts

---

pom.xml
src/main/java/org/eolang/lints/misc/LtTestNotVerb.java
src/test/java/org/eolang/lints/misc/LtTestIsNotVerbTest.java

In this PR I've replaced [Stanford CoreNLP](https://stanfordnlp.github.io/CoreNLP/) (GPL) with [Apache OpenNLP](https://opennlp.apache.org/) (Apache-2.0) in order to comply with dependency license.
closes #257

bug(#257): Apache OpenNLP instead of Stanford Core NLP

---

src/main/resources/org/eolang/lints/names/object-does-not-match-filename.xsl
src/test/resources/org/eolang/lints/packs/object-does-not-match-filename/catches-bad-packaged-name-with-correct-message.yaml
src/test/resources/org/eolang/lints/packs/object-does-not-match-filename/catches-multiple-packaged-names.yaml

In this PR I've updated `object-does-not-match-filename` to compare full program name(`/program/@name`) with object name (counting packages too).
see #296
History:
- **bug(#296): test**
- **bug(#296): compare program with opath**

bug(#296): compare `/program/@name` with packaged object path

---

src/main/java/org/eolang/lints/PkMono.java

In this PR I've removed `LtTestNotVerb` from `PkMono` and left puzzle for getting it back.
see #297

bug(#297): remove `LtTestNotVerb` from PkMono

---

src/test/resources/org/eolang/lints/packs/duplicate-metas/catches-duplicate-unlint.yaml
src/test/resources/org/eolang/lints/packs/duplicate-metas/passes-on-all-unique-unlint.yaml

In this PR I've added test cases for `duplicate-metas.xsl`, that checks the duplication of `unlint` meta.
closes #304

feat(#304): duplicate `unlint` tests

---

src/main/resources/org/eolang/lints/critical/void-attributes-not-higher-than-other.xsl
src/main/resources/org/eolang/motives/critical/void-attributes-not-higher-than-other.md
src/test/resources/org/eolang/lints/packs/void-attributes-not-higher-than-other/allows-all-empty-attributes.yaml
src/test/resources/org/eolang/lints/packs/void-attributes-not-higher-than-other/allows-empty-void-attributes.yaml
src/test/resources/org/eolang/lints/packs/void-attributes-not-higher-than-other/allows-top-void-attributes-in-multiple-objects.yaml
src/test/resources/org/eolang/lints/packs/void-attributes-not-higher-than-other/allows-void-attributes-at-top.yaml
src/test/resources/org/eolang/lints/packs/void-attributes-not-higher-than-other/allows-void-attributes-higher-than-many-other.yaml
src/test/resources/org/eolang/lints/packs/void-attributes-not-higher-than-other/catches-lower-void-attributes-in-multiple-objects.yaml
src/test/resources/org/eolang/lints/packs/void-attributes-not-higher-than-other/catches-void-attributes-at-bottom.yaml
src/test/resources/org/eolang/lints/packs/void-attributes-not-higher-than-other/catches-void-attributes-lower-than-other.yaml

In this PR I've introduced `void-attributes-not-higher-than-other` lint, that issues defect with `critical` severity, if void attribute (`∅`) is located lower than sibling non-void attributes.
closes #292

feat(#292): `void-attributes-not-higher-than-other`

---

.github/workflows/shellcheck.yml
pom.xml
src/main/java/org/eolang/lints/LtByXsl.java
src/main/java/org/eolang/lints/LtUnlint.java
src/main/java/org/eolang/lints/comments/LtAsciiOnly.java
src/main/java/org/eolang/lints/critical/LtIncorrectAlias.java
src/main/java/org/eolang/lints/errors/LtAtomIsNotUnique.java
src/main/java/org/eolang/lints/errors/LtObjectIsNotUnique.java
src/main/java/org/eolang/lints/misc/LtTestNotVerb.java
src/test/java/org/eolang/lints/errors/LtObjectIsNotUniqueTest.java
src/test/java/org/eolang/lints/misc/LtTestNotVerbTest.java

In this PR I've substituted the usage of `XML#xpath()` and `XML#nodes()` in favor of `Xnav` library.
closes #264
History:
- **feat(#264): xnav in LtAsciiOnly**
- **feat(#264): xnav in LtTestNotVerb**
- **feat(#264): xnav in LtObjectIsNotUnique**
- **feat(#264): xnav in LtByXsl**
- **feat(#264): puzzle**

feat(#264): Xnav instead of `XML#xpath()` and `XML#nodes()`

---

src/main/java/org/eolang/lints/Program.java
src/main/java/org/eolang/lints/Programs.java
src/test/java/org/eolang/lints/ProgramTest.java
src/test/java/org/eolang/lints/ProgramsTest.java

In this PR I've added method `#without(name)` to `Program` and `Programs`, that excludes lints by supplied name.
closes #319
History:
- **feat(#319): Program.without()**
- **feat(#319): Programs**
- **feat(#319): disabled**

feat(#319): `.without(name)` to disable lints programmatically

---

src/main/java/org/eolang/lints/PkByXsl.java
src/main/java/org/eolang/lints/PkMono.java
src/test/java/org/eolang/lints/PkMonoTest.java

In this PR I've wrapped lints in `PkMono` with `LtUnlint`. Besides that, I added tests that check that each lint can be unlinted.
closes #307
History:
- **bug(#307): +LtUnlint**
- **bug(#307): can be unlinted**
- **bug(#307): filter LtIncorrectUnlint**
- **bug(#307): clean for qulice**

bug(#307): check for `LtUnlint` in `PkMono`

---

src/main/java/org/eolang/lints/LtUnlintNonExistingDefect.java
src/main/java/org/eolang/lints/PkMono.java
src/main/resources/org/eolang/motives/misc/unlint-non-existing-defect.md
src/test/java/org/eolang/lints/LtUnlintNonExistingDefectTest.java
src/test/java/org/eolang/lints/ProgramTest.java
src/test/resources/org/eolang/lints/canonical.eo

In this PR I've added new lint: `unlint-non-existing-defect`, that issues defects with warning severity, in case of usage of `+unlint` meta to suppress non-existing defects.
closes #322
History:
- **feat(#322): unlint-non-existing-defect**
- **feat(#322): clean for qulice**

feat(#322): `unlint-non-existing-defect` lint

---

src/test/resources/org/eolang/lints/canonical.eo

In this PR i've removed an unlint of `object-does-not-match-filename` in `canonical.eo`, in order to fix the master branch, after [introducing `unlint-non-existing-defect` lint](https://github.com/objectionary/lints/commit/8d09f407d0b0a190144126f4b4e63fea7573e80b) and [breaking changes in `object-does-not-match-filename`](https://github.com/objectionary/lints/commit/7a53b4b526ab142607a396a72c3cb763c9fc4ddc).
closes #357

bug(#357): fix unlints in canonical.eo

---

src/main/resources/org/eolang/lints/misc/sprintf-without-formatters.xsl
src/main/resources/org/eolang/lints/misc/wrong-sprintf-arguments.xsl
src/main/resources/org/eolang/motives/misc/sprintf-without-formatters.md
src/test/resources/org/eolang/lints/packs/sprintf-without-formatters/catches-multiple-sprintf.yaml
src/test/resources/org/eolang/lints/packs/sprintf-without-formatters/catches-sprintf-without-formatters-and-with-args.yaml
src/test/resources/org/eolang/lints/packs/sprintf-without-formatters/catches-sprintf-without-formatters.yaml
src/test/resources/org/eolang/lints/packs/sprintf-without-formatters/passes-sprintf-with-formatters.yaml

In this PR I've implemented new lint: `sprintf-without-formatters`, that issues defect with `warning` severity, if there is no formatters in the template string of `Q.org.eolang.txt.sprintf` object.
closes #258
History:
- **feat(#258): sprintf-without-formatters**
- **feat(#258): motive, celan for xcop**

feat(#258): `sprintf-without-formatters` lint

---

src/main/java/org/eolang/lints/Defect.java
src/main/java/org/eolang/lints/DfContext.java
src/main/java/org/eolang/lints/LtByXsl.java
src/main/resources/org/eolang/funcs/defect-context.xsl
src/main/resources/org/eolang/lints/critical/application-duality.xsl
src/test/java/org/eolang/lints/DfContextTest.java
src/test/java/org/eolang/lints/LtByXslTest.java
src/test/resources/org/eolang/lints/packs/application-duality/prints-context-when-lines-empty.yaml
src/test/resources/org/eolang/lints/xmir-with-application-duality.xml

In this PR I've implemented Proof Of Concept of printing defect's context, if inspected XMIR doesn't have `@line` attributes inside.
see #343
History:
- **feat(#343): print first N chars**
- **feat(#343): poc**

feat(#343): POC: show defect context if `@line` attributes are empty

---

REUSE.toml
src/main/java/org/eolang/lints/DfContext.java
src/main/java/org/eolang/lints/LtInconsistentArgs.java
src/main/resources/org/eolang/funcs/defect-context.xsl
src/main/resources/org/eolang/motives/misc/inconsistent-args.md
src/test/java/org/eolang/lints/DfContextTest.java
src/test/java/org/eolang/lints/LtInconsistentArgsTest.java
src/test/resources/org/eolang/lints/packs/application-duality/prints-context-when-lines-empty.yaml
src/test/resources/org/eolang/lints/xmir-with-application-duality.xml

In this PR I've introduced new lint: `inconsistent-args`, that reports `warning`-s for objects with the same `@base`, but with different number of arguments passed in it in the scope of all programs under analysis.
closes #259
History:
- **feat(#259): test**
- **feat(#259): report localized**
- **feat(#259): opposite refs**
- **feat(#259): allows test**
- **feat(#259): typo**
- **feat(#259): typo**
- **feat(#259): multiple programs**
- **feat(#259): whole merge, invert, report**
- **feat(#259): clean for qulice**

feat(#259): `inconsistent-args` lint

---

src/main/resources/org/eolang/lints/metas/mandatory-spdx.xsl
src/main/resources/org/eolang/lints/metas/unknown-metas.xsl
src/main/resources/org/eolang/motives/metas/mandatory-spdx.md
src/test/java/matchers/GrammarMatcher.java
src/test/java/org/eolang/lints/ProgramTest.java
src/test/resources/org/eolang/lints/canonical.eo
src/test/resources/org/eolang/lints/packs/mandatory-spdx/catches-missing-spdx.yaml
src/test/resources/org/eolang/lints/packs/mandatory-spdx/passes-on-spdx-presence.yaml

In this PR I've introduced new lint: `mandatory-spdx`, that issues defect with `warning` severity, if `+spdx` meta is missing.
see #354

feat(#354): `mandatory-spdx` lint

---

src/test/java/org/eolang/lints/LtUnlintNonExistingDefectTest.java
src/test/java/org/eolang/lints/LtUnlintNonExistingDefectWpaTest.java

In this PR I've added disabled tests for found bug in `unlint-non-existing-defect` about ignoring `+unlint` meta for defect from the other scope: single program scope should ignore WPA unlints, while WPA - unlints from single program scope.
related to #368

bug(#368): disabled tests for bug: ignoring unlints from other scope in `unlint-non-existing-defect`

---

src/main/resources/org/eolang/lints/metas/empty-spdx-tail.xsl
src/main/resources/org/eolang/lints/metas/incorrect-spdx.xsl
src/main/resources/org/eolang/motives/metas/empty-spdx-tail.md
src/main/resources/org/eolang/motives/metas/incorrect-spdx.md
src/test/java/matchers/GrammarMatcher.java
src/test/java/org/eolang/lints/ProgramTest.java
src/test/resources/org/eolang/lints/packs/empty-spdx-tail/catches-empty-tail.yaml
src/test/resources/org/eolang/lints/packs/empty-spdx-tail/passes-on-good-tail.yaml
src/test/resources/org/eolang/lints/packs/incorrect-spdx/catches-incorrect-spdx-metas.yaml
src/test/resources/org/eolang/lints/packs/incorrect-spdx/passes-on-good-spdx-metas.yaml
src/test/resources/org/eolang/lints/packs/incorrect-spdx/passes-on-good-spdx.yaml

In this PR I've introduced new lints to check the format of `+sdpx` meta: `incorrect-spdx` and `empty-spdx-tail`.
closes #383
History:
- **feat(#383): incorrect-spdx lint**
- **feat(#383): better message**
- **feat(#383): typo**
- **feat(#383): better message**
- **feat(#383): motive**
- **feat(#383): empty-spdx-tail**
- **feat(#383): motive**

feat(#383): `incorrect-sdpx` and `empty-spdx-tail` lints for `+spdx` meta

---

src/main/java/org/eolang/lints/LtUnlint.java
src/test/java/org/eolang/lints/LtUnlintTest.java

In this PR I've implemented granular unlinting of defects by lines in `+unlint`.
closes #386
History:
- **feat(#386): test**
- **feat(#386): granularity**
- **feat(#386): problematic.clear()**
- **feat(#386): clean for qulice**

feat(#386): granular line unlinting in `+unlint`

---

src/test/java/org/eolang/lints/PkMonoTest.java

In this PR I've updated `PkMonoTest.checksThatLintsCanBeUnlinted` to check decoratee of specific lint to be equal to `LtUnlint`, instead of specific lint to be `LtUnlint` itself.
closes #394

bug(#394): check decoratee of specific lint to be `LtUnlint` in `PkMonoTest.checksThatLintsCanBeUnlinted()`

---

src/main/java/org/eolang/lints/LtIncorrectUnlint.java
src/test/java/matchers/GrammarMatcher.java
src/test/java/org/eolang/lints/LtIncorrectUnlintTest.java

In this PR I've improved defect message in `incorrect-unlint`.
closes #396

bug(#396): clear message in incorrect-unlint

---

src/main/resources/org/eolang/lints/critical/application-duality.xsl
src/test/resources/org/eolang/lints/packs/application-duality/catches-mix-of-as-and-bases-with-inners.yaml

In this PR I've updated the message about `application-duality` to make it more clear, and added one more test case with mix of `@as` and `@base` attributes with inner objects.
closes #409

bug(#409): revised message about `application-duality`

---

src/main/resources/org/eolang/motives/metas/incorrect-spdx.md
src/main/resources/org/eolang/motives/metas/mandatory-spdx.md

In this PR I've extended motives of `incorrect-spdx` and `mandatory-spdx` by adding information about `+spdx` meta structure in XMIR.
closes #419

bug(#419): spdx in XMIR

---

src/main/java/org/eolang/lints/LtIncorrectNumberOfAttrs.java
src/main/java/org/eolang/lints/WpaLints.java
src/main/resources/org/eolang/motives/errors/incorrect-number-of-attributes.md
src/test/java/org/eolang/lints/LtIncorrectNumberOfAttrsTest.java

In this PR I've introduced new lint: `incorrect-number-of-attributes`, that issues `ERROR` defect if the number of provided attributes to object does not match with the number of its declared attributes.
closes #36
History:
- **feat(#36): test**
- **feat(#36): objectDefinitions**
- **feat(#36): scan usages**
- **feat(#36): more tests**
- **feat(#36): packaged fqn, more tests**
- **feat(#36): correct vertical application**
- **feat(#36): clean for qulice**
- **feat(#36): integrate into WpaLints**
- **feat(#36): motive**
- **feat(#36): packagedFqn**
- **feat(#36): more clear**
- **feat(#36): more clear 2x**
- **feat(#36): polish**

feat(#36): incorrect-number-of-attributes

---

.ort.yml
pom.xml
src/main/java/org/eolang/lints/LtUnlint.java

In this PR I've replaced `XML.xpath()` with `Xnav.path()`, and upgraded `xnav` version to `0.1.14`.
closes #392

bug(#392): `Xnav.path()` in LtUnlint

---

src/main/resources/org/eolang/lints/names/duplicate-as-attribute.xsl
src/main/resources/org/eolang/motives/names/duplicate-as-attribute.md
src/test/resources/org/eolang/lints/packs/duplicate-as-attribute/allows-as-distinct-attributes.yaml
src/test/resources/org/eolang/lints/packs/duplicate-as-attribute/allows-only-one-attribute.yaml
src/test/resources/org/eolang/lints/packs/duplicate-as-attribute/allows-when-attributes-empty.yaml
src/test/resources/org/eolang/lints/packs/duplicate-as-attribute/catches-as-duplicates.yaml
src/test/resources/org/eolang/lints/packs/duplicate-as-attribute/checks-only-parent-level-attributes.yaml
src/test/resources/org/eolang/lints/packs/duplicate-as-attribute/reports-line-correctly.yaml

In this PR I've introduced new lint: `duplicate-as-attribute`, which issues `warning` defect if an object in XMIR has duplicate `@as` attributes on its first level of depth.
closes #93

feat(#93): `duplicate-as-attribute` lint

---

src/main/java/org/eolang/lints/LtIncorrectUnlint.java
src/test/java/org/eolang/lints/LtIncorrectUnlintTest.java

In this PR I've updated `LtIncorrectUnlint`, so it understands the unlints with line number e.g: `+unlint comment-too-short:42`.
closes #445
History:
- **feat(#445): tests**
- **bug(#445): split**

bug(#445): `LtIncorrectUnlint` understands unlints with line number

---

.github/workflows/pit.yml
src/main/java/org/eolang/lints/DefectMissing.java
src/main/java/org/eolang/lints/LtUnlintNonExistingDefect.java
src/main/java/org/eolang/lints/LtUnlintNonExistingDefectWpa.java
src/main/java/org/eolang/lints/MatchesLinedUnlint.java
src/test/java/org/eolang/lints/DefectMissingTest.java
src/test/java/org/eolang/lints/LtUnlintNonExistingDefectTest.java
src/test/java/org/eolang/lints/LtUnlintNonExistingDefectWpaTest.java

In this PR I've added support of unlints with line number via `DefectMissing.java` in both: `LtUnlintNonExistingDefect` and `LtUnlintNonExistingDefectWpa`.
closes #447
History:
- **bug(#447): tests**
- **bug(#447): filters correctly in single scope**
- **bug(#447): matches in WPA**
- **bug(#447): more test**
- **bug(#447): check if present**
- **bug(#447): MatchesLinedUnlint**
- **bug(#447): clean for qulice**

bug(#447): `LtUnlintNonExistingDefect` and `LtUnlintNonExistingDefectWpa` understand unlints with line number

---

.github/workflows/pit.yml

In this PR I've configured `pit.yml` workflow to run only on push to the `master` branch, added ticket creation on failures, and increased timeout to 90min.
closes #452

ci(#452): run pit on master only together with failure reporting

---

src/main/java/org/eolang/lints/Defect.java
src/main/java/org/eolang/lints/LtUnlint.java
src/test/java/org/eolang/lints/LtUnlintTest.java
src/test/java/org/eolang/lints/MonoLintsTest.java
src/test/java/org/eolang/lints/ProgramTest.java
src/test/java/org/eolang/lints/ProgramsTest.java
src/test/resources/org/eolang/lints/packs/single/noname-attribute/catches-only-one-noname.yaml

In this PR I've fixed the bug with defect duplication, caused by `LtUnlint` mapping, and added bunch of tests.
see #451
History:
- **bug(#451): test case**
- **bug(#451): broken**
- **bug(#451): show**
- **bug(#451): test MonoLints**
- **bug(#451): more tests**
- **bug(#451): clean for qulice**

bug(#451): Defect duplication fixed in `LtUnlint`

---

.gitignore
pom.xml
src/main/java/org/eolang/lints/LtReservedName.java
src/main/java/org/eolang/lints/MonoLints.java
src/main/resources/org/eolang/motives/names/reserved-name.md
src/test/java/org/eolang/lints/LtReservedNameTest.java

In this PR I've implemented new lint: `reserved-name`, that issues defect with `warning` severity if object uses name, already reserved by object in `org.eolang.*` package.
closes #165
History:
- **feat(#165): start**
- **feat(#165): more tests**
- **feat(#165): deep test case, naming check**
- **feat(#165): no args**
- **feat(#165): parsing stream, more tests**
- **feat(#165): nested**
- **feat(#165): pull**
- **feat(#165): motive**
- **feat(#165): report object**

feat(#165): `reserved-name` lint

---

src/main/resources/org/eolang/lints/misc/sparse-decoration.xsl
src/main/resources/org/eolang/motives/misc/sparse-decoration.md
src/test/resources/org/eolang/lints/packs/single/sparse-decoration/allows-sparse-in-tests.yaml

In this PR I updated `sparse-decoration` to stay quiet when `+tests` meta is specified.
closes #459

bug(#459): `sparse-decoration` allowed in tests

---

pom.xml

In this PR I've updated `pit` configuration to exclude large Hadoop HDFS benchmark class `org.apache.hadoop.hdfs.server.namenode.FSNamesystem` from mutation checks.
closes #473

bug(#473): pit exclude hadoop class

---

src/main/resources/org/eolang/lints/critical/named-object-abstract-nested.xsl
src/main/resources/org/eolang/motives/critical/named-object-abstract-nested.md
src/test/resources/org/eolang/lints/packs/single/named-object-abstract-nested/allows-chain-of-bases.yaml
src/test/resources/org/eolang/lints/packs/single/named-object-abstract-nested/allows-eo-in-canonical-form.yaml
src/test/resources/org/eolang/lints/packs/single/named-object-abstract-nested/allows-eo-with-syntax-sugar.yaml
src/test/resources/org/eolang/lints/packs/single/named-object-abstract-nested/allows-named-object-on-the-first-level.yaml
src/test/resources/org/eolang/lints/packs/single/named-object-abstract-nested/allows-nested-bases.yaml
src/test/resources/org/eolang/lints/packs/single/named-object-abstract-nested/catches-multiple-named-nested-abstract.yaml
src/test/resources/org/eolang/lints/packs/single/named-object-abstract-nested/catches-named-object-nested-in-abstract.yaml

In this PR I've introduced new lint: `named-object-abstract-nested`, that issues defect with `critical` severity, if named object is nested deeper more than one level inside abstract object.
closes #291
History:
- **feat(#291): start**
- **feat(#291): EO forms**
- **feat(#291): more tests**
- **feat(#291): motive**

feat(#291): `named-object-abstract-nested` lint

---

src/main/resources/org/eolang/lints/names/object-does-not-match-filename.xsl
src/test/resources/org/eolang/lints/packs/single/object-does-not-match-filename/allows-good-name-relatively-with-dots-in-name.yaml
src/test/resources/org/eolang/lints/packs/single/object-does-not-match-filename/allows-good-name-relatively.yaml
src/test/resources/org/eolang/lints/packs/single/object-does-not-match-filename/catches-bad-name-relatively.yaml
src/test/resources/org/eolang/lints/packs/single/object-does-not-match-filename/catches-bad-name-with-many-dots.yaml
src/test/resources/org/eolang/lints/packs/single/object-does-not-match-filename/catches-name-with-dots.yaml

In this PR I've updated `object-does-not-match-filename` to check only `program/@source` contains object name, instead of checking full path `program/@source` starts with object name.
closes #460

bug(#460): relatively `program/@source` check in `object-does-not-match-filename`

---

src/main/java/org/eolang/lints/Defect.java
src/main/java/org/eolang/lints/DfContext.java
src/main/java/org/eolang/lints/LtByXsl.java
src/test/java/org/eolang/lints/DefectTest.java
src/test/java/org/eolang/lints/LtByXslTest.java

In this PR I've added new method into `Defect`: `Defect.experimental()`, which serves as indicator of experimental lint.
closes #476
History:
- **feat(#476): Defect.experimental()**
- **feat(#476): clean for qulice**

feat(#476): `Defect.experimental()`

---

src/main/resources/org/eolang/lints/errors/unused-void-attr.xsl
src/main/resources/org/eolang/motives/errors/unused-void-attr.md
src/test/resources/org/eolang/lints/packs/single/unused-void-attr/allows-unused-voids-in-atom.yaml

In this PR I've updated `unused-void-attr` lint to not complain about unused void attributes, if the formation itself is the atom.
see #482

bug(#482): allow atom formations in `unused-void-attr`

---

src/main/resources/org/eolang/lints/design/no-attribute-formation.xsl
src/main/resources/org/eolang/motives/design/no-attribute-formation.md
src/test/java/org/eolang/lints/ProgramTest.java
src/test/resources/org/eolang/lints/canonical.eo
src/test/resources/org/eolang/lints/packs/single/no-attribute-formation/allows-formation-with-voids.yaml
src/test/resources/org/eolang/lints/packs/single/no-attribute-formation/allows-formation-without-voids-in-tests.yaml
src/test/resources/org/eolang/lints/packs/single/no-attribute-formation/catches-formation-without-voids.yaml

In this PR I've introduced new experimental lint: `no-attribute-formation`, that issues defect with `warning` severity, if formation does not have any void attributes.
closes #379
History:
- **feat(#379): start**
- **feat(#379): ignore in tests**
- **feat(#379): motive**
- **feat(#379): void in canonical**
- **feat(#379): clean up sources**

feat(#379): `no-attribute-formation` experimental lint

---

src/main/resources/org/eolang/lints/names/anonymous-formation.xsl
src/test/resources/org/eolang/lints/packs/single/anonymous-formation/catches-anonymous-with-multiple-formations.yaml

In this PR I've removed defect duplication in `anonymous-formation`, when multiple formations are in the scope.
closes #483

bug(#483): remove defect duplication in `anonymous-formation`

---

pom.xml

In this PR I've updated `jcabi-xml` to `0.34.0` version with feature of re-throwing stylesheet compilation warnings. Thus, our 
XSL pipeline will be more strict.
closes #488

bug(#488): jcabi-xml up to `0.34.0`

---

README.md

This task solves the problem that when building a project locally, a strange error may occur due to an incorrect version of xcop
The information in the README about the minimum version has been added here

feat(#486): add info about min xcop version

---

src/test/java/org/eolang/lints/SourceTest.java

In this PR I've fixed the bug with lint time formatting, and added new test to validate it.
closes #510
History:
- **bug(#510): start**
- **bug(#510): two tests**

bug(#510): correct Lint time formatting in benchmark

---

src/main/java/org/eolang/lints/LtAtomIsNotUnique.java
src/main/java/org/eolang/lints/LtObjectIsNotUnique.java

In this PR I've placed usage of `.one(path)` to make XML navigation more strict, where it can be done.
closes #493

feat(#493): Xnav.one(path) for fail fast

---

src/main/resources/org/eolang/lints/errors/empty-object.xsl
src/test/resources/org/eolang/lints/packs/single/empty-object/allows-lambda-object-in-atom.yaml
src/test/resources/org/eolang/lints/packs/single/empty-object/cathes-lambda-object-outside-atom.yaml

It seems to be in the eo repository in the file https://github.com/objectionary/eo/blob/master/eo-parser/src/main/resources/org/eolang/parser/_funcs.xsl there is a problem with the atom function, as it checks that the nested one, not the current one, has the name `lambda`

feat(#412): removed the empty object warning for lambda objects

---

src/main/resources/org/eolang/lints/misc/sprintf-without-formatters.xsl
src/test/resources/org/eolang/lints/packs/single/sprintf-without-formatters/catches-sprintf-with-incorrect-formatter.yaml

In this PR I've updated defect text in the `sprintf-without-formatters` to list all the supported formatters.
see #519

bug(#519): list all supported formatters in the `sprintf-without-formatters`

---

src/main/java/org/eolang/lints/LtInconsistentArgs.java
src/test/resources/org/eolang/lints/packs/wpa/inconsistent-args/catches-inconsistency-across-programs-with-clash-message.yaml

In this PR I've added information about arguments consistency clashes in other objects from found problematic object in `LtInconsistentArgs`.
see #518
History:
- **bug(#518): clashes**
- **bug(#518): clashes**
- **bug(#518): clash information**

bug(#518): list clashes with other objects in `LtInconsistentArgs`

---

src/main/java/org/eolang/lints/Program.java
src/main/java/org/eolang/lints/ScopedDefects.java
src/main/java/org/eolang/lints/Source.java
src/test/java/org/eolang/lints/ProgramTest.java
src/test/java/org/eolang/lints/ScopedDefectsTest.java
src/test/java/org/eolang/lints/SourceTest.java

In this PR I've added new class `ScopedDefects` to classify Defect messages by appending scope to their rule name.
see #518
History:
- **bug(#518): test first**
- **bug(#518): ScopedDefects**

bug(#518): `ScopedDefects` to categorize lint scopes in the stdout

---

src/main/java/org/eolang/lints/Defect.java
src/main/java/org/eolang/lints/DfContext.java
src/main/java/org/eolang/lints/LtWpaUnlint.java
src/main/java/org/eolang/lints/ScopedDefects.java
src/test/java/org/eolang/lints/DefectTest.java
src/test/java/org/eolang/lints/WpaStory.java
src/test/resources/org/eolang/lints/packs/wpa/atom-is-not-unique/catches-atom-fqn-duplicates-within-same-package.yaml
src/test/resources/org/eolang/lints/packs/wpa/atom-is-not-unique/catches-atom-fqn-duplicates.yaml
src/test/resources/org/eolang/lints/packs/wpa/atom-is-not-unique/catches-duplicates-in-single-program.yaml
src/test/resources/org/eolang/lints/packs/wpa/atom-is-not-unique/catches-nested-duplicates.yaml
src/test/resources/org/eolang/lints/packs/wpa/inconsistent-args/catches-arguments-inconsistency.yaml
src/test/resources/org/eolang/lints/packs/wpa/inconsistent-args/catches-inconsistency-across-programs-with-alias.yaml
src/test/resources/org/eolang/lints/packs/wpa/inconsistent-args/catches-inconsistency-across-programs-with-clash-message.yaml
src/test/resources/org/eolang/lints/packs/wpa/inconsistent-args/catches-inconsistency-across-programs.yaml
src/test/resources/org/eolang/lints/packs/wpa/incorrect-alias/catches-broken-alias.yaml
src/test/resources/org/eolang/lints/packs/wpa/incorrect-number-of-attributes/catches-incorrect-attributes-in-vertical-application.yaml
src/test/resources/org/eolang/lints/packs/wpa/incorrect-number-of-attributes/catches-incorrect-number-of-attributes.yaml
src/test/resources/org/eolang/lints/packs/wpa/object-is-not-unique/catches-duplicates.yaml

In this PR I've updated terminology in the `Defect` class, from `Defect.program()` to `Defect.object()`, so it synced with 
new XMIR semantics.
closes #525

bug(#525): `Defect.program()` -> `Defect.object()`

---

src/main/resources/org/eolang/lints/names/anonymous-formation.xsl
src/test/resources/org/eolang/lints/packs/single/anonymous-formation/allows-anonymous-accessing-its-own-void-in-auto.yaml
src/test/resources/org/eolang/lints/packs/single/anonymous-formation/allows-anonymous-accessing-its-own-void-with-dot-notation.yaml
src/test/resources/org/eolang/lints/packs/single/anonymous-formation/allows-anonymous-accessing-its-own-void.yaml
src/test/resources/org/eolang/lints/packs/single/anonymous-formation/catches-anonymous-accessing-undefined-with-proper-message.yaml

In this PR I've fixed the bug with false positives when anonymous formation accessed its own void attributes in the deeper scopes.
see #516
History:
- **bug(#516): passes on access its own voids**
- **bug(#516): passes too**
- **bug(#516): adjust seq steps**
- **bug(#516): catchy test**
- **bug(#516): hardcode void**
- **bug(#516): passes**
- **bug(#516): clean for qulice**

bug(#516): check void matches in `anonymous-formation`

---

src/test/java/org/eolang/lints/LtByXslTest.java
src/test/java/org/eolang/lints/WpaStory.java
src/test/resources/org/eolang/lints/packs/single/anonymous-formation/allows-anonymous-accessing-defined-object-inside.yaml
src/test/resources/org/eolang/lints/packs/single/anonymous-formation/allows-anonymous-formation-with-correct-access.yaml
src/test/resources/org/eolang/lints/packs/single/anonymous-formation/allows-anonymous-using-defined-object.yaml
src/test/resources/org/eolang/lints/packs/single/anonymous-formation/allows-named-formation-via-autonamed.yaml
src/test/resources/org/eolang/lints/packs/single/duplicate-aliases/catches-alias-duplicates.yaml
src/test/resources/org/eolang/lints/packs/single/duplicate-metas/catches-duplicate-metas.yaml
src/test/resources/org/eolang/lints/packs/single/duplicate-names/multi-anonymous.yaml
src/test/resources/org/eolang/lints/packs/single/incorrect-rt-parts/catches-incorrect-rt-parts.yaml
src/test/resources/org/eolang/lints/packs/single/mandatory-package/catches-mandatory-package-meta.yaml
src/test/resources/org/eolang/lints/packs/single/many-free-attributes/catches-many-free-attrs.yaml
src/test/resources/org/eolang/lints/packs/single/package-contains-multiple-parts/catches-package-contains-multiple-parts.yaml
src/test/resources/org/eolang/lints/packs/single/self-referencing/self-referencing-no-catch.yaml
src/test/resources/org/eolang/lints/packs/single/unique-metas/allows-single-package.yaml
src/test/resources/org/eolang/lints/packs/single/unique-metas/catches-home-duplicate.yaml
src/test/resources/org/eolang/lints/packs/single/unique-metas/catches-package-duplicate.yaml
src/test/resources/org/eolang/lints/packs/single/unknown-metas/catches-unknown-metas.yaml
src/test/resources/org/eolang/lints/packs/single/unknown-rt/allows-good-rt.yaml
src/test/resources/org/eolang/lints/packs/single/unknown-rt/catches-unknown-rt.yaml
src/test/resources/org/eolang/lints/packs/single/unsorted-metas/catches-metas-unsorted.yaml
src/test/resources/org/eolang/lints/packs/single/wrong-sprintf-arguments/allows-percentage-sign.yaml
src/test/resources/org/eolang/lints/packs/wpa/inconsistent-args/allows-consistent-arguments.yaml
src/test/resources/org/eolang/lints/packs/wpa/inconsistent-args/catches-inconsistency-across-programs-with-clash-message.yaml
src/test/resources/org/eolang/lints/packs/wpa/incorrect-number-of-attributes/allows-correct-attributes-in-vertical-application.yaml
src/test/resources/org/eolang/lints/packs/wpa/incorrect-number-of-attributes/allows-correct-number-of-attributes-in-same-program.yaml
src/test/resources/org/eolang/lints/packs/wpa/incorrect-number-of-attributes/allows-correct-number-of-attributes.yaml
src/test/resources/org/eolang/lints/packs/wpa/object-is-not-unique/allows-non-unique-multiple-objects-in-different-packages.yaml

In this pull I've added error checks for all EO snippets we have in YAML test packs in both scopes: single and WPA.
closes #530
History:
- **bug(#530): validatesEoPacksForErrors**
- **bug(#530): Xnav**
- **bug(#530): error check in WpaStory**
- **bug(#530): clean**

bug(#530): validate EO snippets for errors in YAML packs

---

.github/workflows/jmh.yml
.gitignore

Pins `jmh-benchmark-action` to stable version `v1` and updates `.gitignore` to exclude `.aidy` files.
Closes #550

ci(#550): Pin jmh-benchmark-action to v1 instead of main

---

src/main/resources/org/eolang/funcs/special-name.xsl
src/main/resources/org/eolang/lints/misc/duplicate-names-in-diff-context.xsl
src/test/resources/org/eolang/lints/packs/single/duplicate-names-in-diff-context/allows-special-names.yaml
src/test/resources/org/eolang/lints/packs/single/duplicate-names-in-diff-context/prints-context-when-lines-empty.yaml

In this pull request, I fixed a bug where the `duplicate-names-in-diff-context` lint was incorrectly warning about the name `lambda`. I also tweaked its logic so it works when `line` values are empty - previously, it was throwing an error in that case

fix(#577): duplicate-names-in-diff-context will not trigger on specials

---

src/main/resources/org/eolang/lints/misc/duplicate-names-in-diff-context.xsl
src/test/resources/org/eolang/lints/packs/single/duplicate-names-in-diff-context/allows-duplicates-in-voids.yaml

In this PR I've updated `duplicate-names-in-diff-context` to exclude void attributes from analysis.
see #578
History:
- **bug(#578): test case**
- **bug(#578): passes**

bug(#578): void attribute exclusion in `duplicate-names-in-diff-context`

---

src/main/resources/org/eolang/lints/misc/redundant-object.xsl
src/test/resources/org/eolang/lints/packs/single/redundant-object/allows-reused-via-dot-notation.yaml
src/test/resources/org/eolang/lints/packs/single/redundant-object/catches-redundant-with-dot-notation.yaml

In this PR I've fixed the bug with `redundant-object` lint, where usage regex was not match object chaining via 2+ `.`. For instance: `$.str.as-bytes.size.eq`. Now we count it as an object usage.
see #606

bug(#606): `redundant-object` usage regex supports dot chaining

---

src/main/resources/org/eolang/lints/misc/redundant-object.xsl
src/test/resources/org/eolang/lints/packs/single/redundant-object/respects-constants.yaml

In this PR I've updated `redundant-object` lint to not complain about object constants, like `name!`.
see #607

bug(#607): `redundant-object` respects constants

---

pom.xml
src/test/java/org/eolang/lints/LtReservedNameTest.java
src/test/java/org/eolang/lints/ReservedNamesTest.java

In this PR I've moved home object names processing, from default build lifecycle, to the `deep` profile.
closes #608

bug(#608): reserved names processing in deep profile

---

src/main/resources/org/eolang/lints/misc/redundant-object.xsl
src/test/resources/org/eolang/lints/packs/single/redundant-object/allows-top-unused.yaml

In this PR I've updated `redundant-object` not to complain about top object being unused.
see #609
History:
- **bug(#609): test**
- **bug(#609): check id**

bug(#609): `redundant-object` allows top object being unused
